import {all,read,write,remove,saveBatch} from './db.js';
import {validateTranscript,validatePreferences,validateBackup} from './validate.js';
const main=document.querySelector('#main'),modal=document.querySelector('#modal'),audio=document.querySelector('#audio');
const LANG={en:'英语',fr:'法语',ja:'日语'},GOTHIC='"Hiragino Kaku Gothic ProN","Yu Gothic",Meiryo,sans-serif',MINCHO='"Hiragino Mincho ProN","Yu Mincho",serif',BASE=new URL('./',import.meta.url);
let prefs=validatePreferences((await read('settings','preferences'))?.value);
let episode=null,objectURL=null,view='library',filter='',current=-1,wordCurrent=-1,immersive=false,follow=true,clipEnd=null,toastTimer,backend=false,jobTimer,modalSerial=0;
const $=s=>document.querySelector(s);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function time(v){const n=Math.max(0,Math.floor(Number(v)||0));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;}
const size=v=>v>1048576?`${(v/1048576).toFixed(1)} MB`:`${Math.ceil(v/1024)} KB`;
function on(s,event,fn){$(s)?.addEventListener(event,fn);}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4000);}
function report(e){toast(e?.name==='QuotaExceededError'?'设备空间不足，请先导出备份并清理音频。':e.message||'操作未完成，请重试。');console.error(e);}
function applyPrefs(){document.documentElement.style.setProperty('--jp-font',prefs.font==='mincho'?MINCHO:GOTHIC);document.documentElement.style.setProperty('--imm-font',prefs.immFont==='gothic'?GOTHIC:MINCHO);document.body.classList.toggle('hide-ruby',!prefs.reading);document.body.classList.toggle('hide-translations',!prefs.translation);audio.playbackRate=Number(prefs.rate)||1;}
async function savePrefs(){await write('settings',{id:'preferences',value:prefs});applyPrefs();}
function resetClip(){if(clipEnd!==null)audio.pause();clipEnd=null;}
function closeModal(){resetClip();modalSerial++;modal.close();clearInterval(jobTimer);jobTimer=null;}
function openModal(title,body){resetClip();modalSerial++;clearInterval(jobTimer);jobTimer=null;modal.innerHTML=`<div class="dialog-head"><h2>${esc(title)}</h2><button id="close-modal" aria-label="关闭">×</button></div>${body}`;if(!modal.open)modal.showModal();on('#close-modal','click',closeModal);}
modal.addEventListener('cancel',()=>{resetClip();modalSerial++;clearInterval(jobTimer);jobTimer=null;});
function setNav(){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function exportTranscript(e){download(new Blob([JSON.stringify({format:'tingye-transcript-v1',version:1,title:e.title,language:e.language,duration:e.duration,audio:{filename:e.filename,bytes:e.audio.size},segments:e.segments||[]},null,2)],{type:'application/json'}),`${e.title}.tingye.json`);}
async function probe(blob){return new Promise(resolve=>{const a=document.createElement('audio'),url=URL.createObjectURL(blob);let done=false;const finish=d=>{if(done)return;done=true;URL.revokeObjectURL(url);resolve(Number.isFinite(d)?d:0);};a.preload='metadata';a.src=url;a.onloadedmetadata=()=>finish(a.duration);a.onerror=()=>finish(0);setTimeout(()=>finish(0),6000);});}
async function storeAudio(file,language,title){if(!file?.size)throw Error('请选择一个非空音频文件。');if(file.size>350*1048576)throw Error('每段音频不能超过 350 MB。');const e={id:crypto.randomUUID(),title:title||file.name.replace(/\.[^.]+$/,''),filename:file.name,language,audio:file,duration:await probe(file),created:Date.now(),segments:[],progress:0,bookmarks:[]};await write('episodes',e);return e;}
async function attachTranscript(e,data){validateTranscript(data);if(e.duration&&data.segments.some(s=>s.end>e.duration+2))throw Error('时间轴超过音频长度，请选择对应的音频。');e.language=data.language;e.segments=data.segments;e.duration=e.duration||data.duration||0;await write('episodes',e);if(episode?.id===e.id){episode=e;current=-1;wordCurrent=-1;}return e;}
async function renderLibrary(){view='library';setNav();const collection=(await all('episodes')).sort((a,b)=>b.created-a.created),episodes=collection.filter(e=>!filter||e.language===filter);main.innerHTML=`<section class="intro"><h1>我的声音</h1><p>把喜欢的音频，留在自己手机里。</p></section><div class="actions"><button class="primary" id="add-audio">＋ 导入音频</button><button class="secondary" id="import-script">导入逐字稿</button></div><div class="filters">${[['','全部'],...Object.entries(LANG)].map(([c,n])=>`<button class="chip ${filter===c?'active':''}" data-filter="${c}">${n}</button>`).join('')}</div>${episodes.length?`<div class="stack library-list">${episodes.map(e=>`<button class="episode" data-episode="${e.id}"><span class="episode-mark ${e.language}">${{en:'EN',fr:'FR',ja:'日'}[e.language]}</span><span class="episode-info"><span class="episode-title">${esc(e.title)}</span><span class="episode-meta">${LANG[e.language]} · ${time(e.duration)} · ${e.segments?.length?'已有逐字稿':'待导入逐字稿'}</span><span class="progress-line"><span style="width:${Math.min(100,(e.progress||0)/Math.max(e.duration||1,1)*100)}%"></span></span></span></button>`).join('')}</div>`:`<div class="empty"><div class="empty-icon" aria-hidden="true">♫</div><h2>${filter?'还没有'+LANG[filter]+'音频':'添加第一段声音'}</h2><p>从手机「文件」选择音频，再导入电脑生成的逐字稿。</p><button class="primary" id="empty-add">导入音频</button></div>`}`;on('#add-audio','click',importAudio);on('#empty-add','click',importAudio);on('#import-script','click',()=>importScript());document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderLibrary();});document.querySelectorAll('[data-episode]').forEach(b=>b.onclick=()=>openEpisode(b.dataset.episode));}
function importAudio(){openModal('导入音频',`<label for="local-audio">音频文件</label><input id="local-audio" type="file" accept="audio/*,.mp3,.m4a,.wav,.ogg,.flac,.opus"><label for="audio-title">名称</label><input id="audio-title" placeholder="选好文件后可修改名称"><label for="language">音频语言</label><select id="language">${Object.entries(LANG).map(([c,n])=>`<option value="${c}">${n}</option>`).join('')}</select><p class="note">音频保存在当前设备。电脑生成的逐字稿可稍后导入。</p><button class="primary full" id="save-audio">保存到本机</button>`);on('#local-audio','change',()=>$('#audio-title').value=$('#local-audio').files[0]?.name.replace(/\.[^.]+$/,'')||'');on('#save-audio','click',async()=>{const b=$('#save-audio');b.disabled=true;try{const e=await storeAudio($('#local-audio').files[0],$('#language').value,$('#audio-title').value.trim());closeModal();await renderLibrary();toast('音频已保存在本机');await navigator.storage?.persist?.();await openEpisode(e.id);}catch(error){report(error);b.disabled=false;}});}
async function importScript(preselected){const episodes=await all('episodes');openModal('导入逐字稿',`<label for="script-file">电脑导出的逐字稿</label><input id="script-file" type="file" accept=".json,application/json"><label for="script-episode">对应的音频</label><select id="script-episode"><option value="new">同时选择一个新音频</option>${episodes.map(e=>`<option value="${e.id}" ${e.id===preselected?'selected':''}>${esc(e.title)}</option>`).join('')}</select><div id="script-new-audio" ${preselected?'hidden':''}><label for="script-audio">音频文件</label><input id="script-audio" type="file" accept="audio/*,.mp3,.m4a,.wav,.flac,.ogg"></div><p class="note">请选择同一段音频，确保文字与声音的位置对应。</p><button class="primary full" id="attach-script">导入到本机</button>`);on('#script-episode','change',()=>$('#script-new-audio').hidden=$('#script-episode').value!=='new');on('#attach-script','click',async()=>{const b=$('#attach-script');b.disabled=true;let created=null;try{const file=$('#script-file').files[0];if(!file)throw Error('请选择逐字稿文件。');if(file.size>30*1048576)throw Error('逐字稿文件过大。');const data=validateTranscript(JSON.parse(await file.text()));let e;if($('#script-episode').value==='new'){const f=$('#script-audio').files[0];if(!f)throw Error('请选择对应的音频。');if(data.audio?.bytes&&data.audio.bytes!==f.size)throw Error('音频大小与逐字稿记录不同，请重新选择。');e=await storeAudio(f,data.language,data.title);created=e.id;}else{e=await read('episodes',$('#script-episode').value);if(data.audio?.bytes&&data.audio.bytes!==e.audio.size)throw Error('音频大小与逐字稿记录不同，请重新选择。');}await attachTranscript(e,data);closeModal();await openEpisode(e.id);toast('逐字稿和时间轴已保存');}catch(error){if(created)await remove('episodes',created);report(error);b.disabled=false;}});}

async function openEpisode(id,initialPosition){resetClip();const e=await read('episodes',id);if(!e)throw Error('找不到这段音频。');if(episode?.id!==id){await saveProgress();audio.pause();if(objectURL)URL.revokeObjectURL(objectURL);objectURL=URL.createObjectURL(e.audio);episode=e;audio.src=objectURL;audio.onloadedmetadata=()=>{const pos=Math.min(initialPosition??e.progress??0,Math.max(0,audio.duration-.1));if(pos>0)audio.currentTime=pos;updatePlayback();};current=-1;wordCurrent=-1;}else{episode=e;if(Number.isFinite(initialPosition)){current=-1;audio.currentTime=initialPosition;}}view='player';follow=true;setNav();renderPlayer();location.hash=`audio/${id}`;}
function wordsHTML(s,index){if(!s.words?.length)return esc(s.text);return s.words.map((w,j)=>`<span class="word" role="button" tabindex="0" aria-label="${esc(w.text.trim())}，查看词卡" data-word="${index}:${j}">${w.reading?`<ruby>${esc(w.text)}<rt>${esc(w.reading)}</rt></ruby>`:esc(w.text)}</span>`).join('');}
function transportHTML(){return `<div class="seek-row"><span id="elapsed">${time(audio.currentTime)}</span><input id="seek" type="range" min="0" max="${episode.duration||1}" step="0.1" value="${audio.currentTime||0}" aria-label="播放位置"><span>${time(episode.duration)}</span></div><div class="transport"><button data-action="repeat" aria-label="重听当前句">重听</button><button data-action="prev" aria-label="上一句">‹</button><button class="play" data-action="play" aria-label="${audio.paused?'播放':'暂停'}">${audio.paused?'▶':'Ⅱ'}</button><button data-action="next" aria-label="下一句">›</button><button class="immersive" data-action="immerse">${immersive?'退出':'沉浸'}</button></div><div class="dock-more"><button data-action="loop" class="${prefs.loop?'on':''}">单句循环</button><button data-action="pause" class="${prefs.pause?'on':''}">逐句暂停</button><select id="rate" class="compact-select" aria-label="播放速度">${[.6,.75,1,1.25,1.5].map(n=>`<option value="${n}" ${Number(prefs.rate)===n?'selected':''}>${n}×</option>`).join('')}</select></div>`;}
function bindTransport(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const action=b.dataset.action;if(action==='play')togglePlay();if(action==='repeat')jump(Math.max(0,current),true);if(action==='prev')jump(Math.max(0,current-1),true);if(action==='next')jump(Math.min((episode.segments?.length||1)-1,current+1),true);if(action==='immerse')toggleImmersive();if(action==='loop'){prefs.loop=!prefs.loop;await savePrefs();b.classList.toggle('on',prefs.loop);}if(action==='pause'){prefs.pause=!prefs.pause;await savePrefs();b.classList.toggle('on',prefs.pause);}});on('#seek','input',e=>{audio.currentTime=Number(e.target.value);current=-1;clipEnd=null;updatePlayback();});on('#rate','change',async e=>{prefs.rate=Number(e.target.value);await savePrefs();});}
function renderPlayer(){if(!episode)return;$('.player-dock')?.remove();const segments=episode.segments||[];main.innerHTML=`<button class="back" id="back-library">‹ 我的声音</button><div class="player-layout"><section class="player-header"><h1>${esc(episode.title)}</h1><p class="note">${LANG[episode.language]} · ${time(episode.duration)} · ${size(episode.audio.size)}</p><div class="actions"><button class="secondary" id="audio-menu">管理音频</button></div></section><section><div class="reader-tools"><button id="toggle-reading" class="${prefs.reading?'selected':''}">读音</button><button id="toggle-translation" class="${prefs.translation?'selected':''}">译文</button><button id="toggle-follow" class="${follow?'selected':''}">跟随播放</button><button id="add-bookmark">加书签</button></div><div class="transcript" id="transcript">${segments.length?segments.map((s,i)=>`<article class="sentence" data-sentence="${i}"><div class="sentence-time">${time(s.start)}</div><div class="source" lang="${episode.language}">${wordsHTML(s,i)}</div>${s.translation?`<div class="translation">${esc(s.translation)}</div>`:''}</article>`).join(''):`<div class="panel"><h2>音频已保存</h2><p class="note">导入电脑生成的逐字稿后，就能逐句播放和跟读。</p><button class="primary" id="player-import">导入逐字稿</button>${backend?'<button class="secondary section-title" id="player-transcribe">在这台电脑转写</button>':''}</div>`}</div></section></div>`;const dock=document.createElement('div');dock.className='player-dock';dock.innerHTML=`<div class="dock-content">${transportHTML()}</div>`;document.body.append(dock);bindTransport();on('#back-library','click',()=>navigate('library'));on('#audio-menu','click',audioMenu);on('#player-import','click',()=>importScript(episode.id));on('#player-transcribe','click',()=>computerTranscription(episode));on('#toggle-reading','click',async()=>{prefs.reading=!prefs.reading;await savePrefs();$('#toggle-reading').classList.toggle('selected',prefs.reading);});on('#toggle-translation','click',async()=>{prefs.translation=!prefs.translation;await savePrefs();$('#toggle-translation').classList.toggle('selected',prefs.translation);});on('#toggle-follow','click',()=>{follow=!follow;$('#toggle-follow').classList.toggle('selected',follow);});on('#add-bookmark','click',async()=>{episode.bookmarks??=[];episode.bookmarks.push({time:audio.currentTime,text:segments[current]?.text||time(audio.currentTime)});await write('episodes',episode);toast('书签已保存');});bindWords();current=-1;wordCurrent=-1;updatePlayback();}
function bindWords(){document.querySelectorAll('[data-word]').forEach(el=>{const activate=()=>{const [s,w]=el.dataset.word.split(':').map(Number);showWord(s,w);};el.onclick=activate;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate();}};});}
async function togglePlay(){if(audio.paused){try{await audio.play();}catch{toast('请点击播放，或确认音频可以在手机上打开。');}}else audio.pause();}
function jump(index,play){const s=episode.segments?.[index];if(!s){if(play)togglePlay();return;}clipEnd=null;current=-1;audio.currentTime=s.start+.01;updatePlayback();if(play)audio.play().catch(report);}
function segmentAt(t){const a=episode?.segments||[];let low=0,high=a.length-1,best=-1;while(low<=high){const mid=(low+high)>>1;if(a[mid].start<=t){best=mid;low=mid+1;}else high=mid-1;}return best;}
function updatePlayback(){if(!episode)return;let t=audio.currentTime;const clipping=clipEnd!==null;if(clipping&&t>=clipEnd){audio.pause();clipEnd=null;}const segments=episode.segments||[];if(current>=0&&segments[current]&&!clipping&&!audio.paused&&t>=segments[current].end-.02&&(prefs.loop||prefs.pause)){if(prefs.loop){audio.currentTime=segments[current].start+.01;return;}audio.pause();const next=segments[current+1];if(next)audio.currentTime=next.start;t=audio.currentTime;}const index=segmentAt(t);if(index!==current){document.querySelectorAll('.sentence.active').forEach(el=>el.classList.remove('active'));current=index;wordCurrent=-1;const target=$(`[data-sentence="${index}"]`);target?.classList.add('active');if(follow&&!audio.paused&&view==='player'&&!immersive&&!modal.open)target?.scrollIntoView({behavior:'auto',block:'center'});if(immersive)renderImmersiveSentence();}const s=segments[current],word=s?.words?.findIndex(w=>t>=w.start&&t<w.end)??-1;if(word!==wordCurrent){document.querySelectorAll('.word.current').forEach(el=>el.classList.remove('current'));wordCurrent=word;if(word>=0)document.querySelectorAll(`[data-word="${current}:${word}"]`).forEach(el=>el.classList.add('current'));}if($('#elapsed'))$('#elapsed').textContent=time(t);if($('#seek'))$('#seek').value=t;document.querySelectorAll('[data-action="play"]').forEach(b=>{b.textContent=audio.paused?'▶':'Ⅱ';b.setAttribute('aria-label',audio.paused?'播放':'暂停');});}
async function saveProgress(){if(episode){episode.progress=audio.currentTime||0;await write('progress',{id:episode.id,seconds:episode.progress});}}
audio.addEventListener('timeupdate',updatePlayback);audio.addEventListener('play',updatePlayback);audio.addEventListener('pause',()=>{updatePlayback();saveProgress().catch(report);});audio.addEventListener('ended',()=>{saveProgress().catch(report);updatePlayback();});setInterval(()=>{if(episode&&!audio.paused)saveProgress().catch(report);},3500);document.addEventListener('visibilitychange',()=>{if(document.hidden)saveProgress().catch(report);});
function setImmersiveAccess(active){document.body.style.overflow=active?'hidden':'';main.inert=active;document.querySelector('.app-header').inert=active;document.querySelector('nav').inert=active;}
function toggleImmersive(){
  if(immersive){immersive=false;setImmersiveAccess(false);$('.immersive-mode')?.remove();renderPlayer();return;}
  if(!episode.segments?.length){toast('请先导入逐字稿。');return;}
  immersive=true;setImmersiveAccess(true);
  const panel=document.createElement('section');panel.className='immersive-mode';
  panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','沉浸阅读');
  panel.innerHTML=`<div class="imm-top"><span id="imm-counter"></span><button id="exit-immersive">退出</button></div><div class="imm-body" id="imm-body"></div><div class="imm-bottom">${transportHTML()}</div>`;
  $('.player-dock')?.remove();document.body.append(panel);
  on('#exit-immersive','click',toggleImmersive);bindTransport();renderImmersiveSentence();updatePlayback();$('#exit-immersive').focus();
}
function renderImmersiveSentence(){if(!immersive)return;const index=Math.max(0,current),s=episode.segments[index];$('#imm-counter').textContent=`${index+1} / ${episode.segments.length}`;$('#imm-body').innerHTML=`<div class="source" lang="${episode.language}">${wordsHTML(s,index)}</div>${s.translation?`<div class="translation">${esc(s.translation)}</div>`:''}`;bindWords();wordCurrent=-1;}
async function showWord(si,wi){const s=episode.segments[si],w=s.words[wi];audio.pause();const cards=await all('cards'),saved=cards.find(c=>c.episodeId===episode.id&&c.text===w.text.trim());openModal(w.text.trim(),`<p class="note">${esc(w.reading||'')}</p><p class="card-context">${esc(s.text)}</p><label for="word-note">我的释义或备注</label><textarea id="word-note" rows="3" placeholder="写下你想记住的意思">${esc(saved?.note||'')}</textarea><div class="actions"><button class="secondary" id="listen-word">听这个词</button><button class="primary" id="save-word">${saved?'更新词卡':'保存词卡'}</button></div>`);on('#listen-word','click',()=>{audio.currentTime=w.start;clipEnd=Math.max(w.end,w.start+.15);audio.play().catch(report);});on('#save-word','click',async()=>{try{await write('cards',{id:saved?.id||crypto.randomUUID(),episodeId:episode.id,language:episode.language,text:w.text.trim(),reading:w.reading||'',context:s.text,start:w.start,end:w.end,note:$('#word-note').value.trim(),due:saved?.due||Date.now(),level:saved?.level||0});closeModal();toast('词卡已保存');}catch(e){report(e);}});}
async function audioMenu(){openModal('管理音频',`<div class="stack"><button class="secondary full" id="replace-script">导入或更新逐字稿</button>${backend?'<button class="secondary full" id="retranscribe">在这台电脑重新转写</button>':''}<button class="secondary full" id="export-script" ${episode.segments?.length?'':'disabled'}>导出逐字稿与时间轴</button><button class="secondary full" id="export-audio">导出原音频</button><button class="secondary full" id="show-bookmarks">书签（${episode.bookmarks?.length||0}）</button><button class="danger full" id="delete-audio">删除本机音频</button></div>`);on('#retranscribe','click',()=>computerTranscription(episode));on('#replace-script','click',()=>{closeModal();importScript(episode.id);});on('#export-script','click',()=>exportTranscript(episode));on('#export-audio','click',()=>download(episode.audio,episode.filename||episode.title+'.mp3'));on('#show-bookmarks','click',()=>{openModal('书签',episode.bookmarks?.length?`<div class="stack">${episode.bookmarks.map((b,i)=>`<button class="secondary" data-bookmark="${i}">${time(b.time)} · ${esc(b.text)}</button>`).join('')}</div>`:'<p class="note">播放时点击“加书签”，就能标记一个位置。</p>');document.querySelectorAll('[data-bookmark]').forEach(b=>b.onclick=()=>{closeModal();current=-1;audio.currentTime=episode.bookmarks[Number(b.dataset.bookmark)].time;updatePlayback();});});on('#delete-audio','click',()=>{openModal('删除这段音频？','<p class="note">会删除当前设备上的音频、逐字稿和对应词卡。建议先导出备份。</p><div class="actions"><button class="secondary" id="cancel-delete">保留</button><button class="danger" id="confirm-delete">确认删除</button></div>');on('#cancel-delete','click',closeModal);on('#confirm-delete','click',async()=>{const id=episode.id;audio.pause();episode=null;if(objectURL)URL.revokeObjectURL(objectURL);audio.removeAttribute('src');audio.load();await remove('episodes',id);for(const c of await all('cards'))if(c.episodeId===id)await remove('cards',c.id);$('.player-dock')?.remove();closeModal();navigate('library');});});}

async function renderCards(){view='cards';setNav();$('.player-dock')?.remove();const cards=(await all('cards')).filter(c=>!filter||c.language===filter).sort((a,b)=>a.due-b.due),due=cards.filter(c=>c.due<=Date.now());main.innerHTML=`<section class="intro"><h1>我的词卡</h1><p>${cards.length?`${cards.length} 张词卡 · ${due.length} 张待复习`:'在逐字稿里点一个词，把它留下来。'}</p></section><div class="filters">${[['','全部'],...Object.entries(LANG)].map(([c,n])=>`<button class="chip ${filter===c?'active':''}" data-filter="${c}">${n}</button>`).join('')}</div>${due.length?'<button class="primary" id="start-review">开始复习</button>':''}<div class="stack section-title">${cards.length?cards.map(c=>`<article class="card"><small>${LANG[c.language]}</small><div class="card-word">${esc(c.text)} ${c.reading?`<small>${esc(c.reading)}</small>`:''}</div><p>${esc(c.note||'暂无备注')}</p><p class="card-context">${esc(c.context)}</p><div class="actions"><button class="secondary" data-card-listen="${c.id}">听原词</button><button class="secondary" data-card-edit="${c.id}">编辑</button></div></article>`).join(''):'<div class="empty"><div class="empty-icon" aria-hidden="true">▤</div><h2>还没有词卡</h2><p>打开一段有逐字稿的音频，点击想记住的词。</p><button class="primary" id="cards-library">查看音频</button></div>'}</div>`;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderCards();});on('#cards-library','click',()=>navigate('library'));on('#start-review','click',()=>reviewCards(due));document.querySelectorAll('[data-card-listen]').forEach(b=>b.onclick=()=>listenCard(cards.find(c=>c.id===b.dataset.cardListen)));document.querySelectorAll('[data-card-edit]').forEach(b=>b.onclick=()=>editCard(cards.find(c=>c.id===b.dataset.cardEdit)));}
async function listenCard(card){const e=await read('episodes',card.episodeId);if(!e){toast('原音频已被删除');return;}await openEpisode(e.id,card.start);audio.currentTime=card.start;clipEnd=card.end+.08;audio.play().catch(report);}
function editCard(card){openModal('编辑词卡',`<h2>${esc(card.text)}</h2><label for="edit-note">我的释义或备注</label><textarea id="edit-note" rows="3">${esc(card.note)}</textarea><div class="actions"><button class="primary" id="update-card">保存</button><button class="danger" id="delete-card">删除词卡</button></div>`);on('#update-card','click',async()=>{card.note=$('#edit-note').value.trim();await write('cards',card);closeModal();renderCards();});on('#delete-card','click',async()=>{await remove('cards',card.id);closeModal();renderCards();});}
function reviewCards(cards,index=0){if(index>=cards.length){closeModal();toast('本次复习完成');renderCards();return;}const c=cards[index];openModal(`复习 ${index+1} / ${cards.length}`,`<div class="card-word">${esc(c.text)}</div><p class="card-context">${esc(c.context)}</p><button class="secondary full" id="reveal-card">显示我的备注</button><div id="card-answer" hidden><p>${esc(c.note||'尚未填写备注')}</p><div class="actions"><button class="secondary" id="review-again">还不熟</button><button class="primary" id="review-known">记住了</button></div></div>`);on('#reveal-card','click',()=>{$('#card-answer').hidden=false;$('#reveal-card').hidden=true;});for(const [selector,known] of [['#review-again',false],['#review-known',true]])on(selector,'click',async()=>{c.level=known?Math.min(5,(c.level||0)+1):0;c.due=Date.now()+(known?[1,1,3,7,14,30][c.level]*86400000:600000);await write('cards',c);reviewCards(cards,index+1);});}
async function renderSettings(){view='settings';setNav();$('.player-dock')?.remove();const estimate=await navigator.storage?.estimate?.()||{},persisted=await navigator.storage?.persisted?.()||false,episodes=await all('episodes'),total=episodes.reduce((n,e)=>n+e.audio.size,0);main.innerHTML=`<section class="intro"><h1>设置</h1><p>阅读习惯和本机资料。</p></section><div class="settings-grid"><section class="panel"><h2>日语排版</h2><label for="font">正文字体</label><select id="font"><option value="gothic" ${prefs.font==='gothic'?'selected':''}>黑体</option><option value="mincho" ${prefs.font==='mincho'?'selected':''}>明朝体</option></select><label for="imm-font">沉浸字体</label><select id="imm-font"><option value="gothic" ${prefs.immFont==='gothic'?'selected':''}>黑体</option><option value="mincho" ${prefs.immFont==='mincho'?'selected':''}>明朝体</option></select><p class="source" lang="ja"><ruby>今日<rt>きょう</rt></ruby>も、<ruby>少<rt>すこ</rt></ruby>しずつ。</p></section><section class="panel"><h2>本机保存</h2><p>${episodes.length} 段音频 · ${size(total)}</p><div class="storage-track"><span style="width:${Math.min(100,estimate.quota?(estimate.usage||0)/estimate.quota*100:0)}%"></span></div><p class="note">${persisted?'已获得长期保存权限。':'浏览器资料可能被系统清理。重要音频请同时保存在手机“文件”中，并定期导出备份。'}</p><div class="stack"><button class="secondary full" id="persist-storage">申请长期保存</button><button class="primary full" id="export-backup">导出完整备份</button><button class="secondary full" id="import-backup">恢复备份</button></div></section><section class="panel"><h2>在手机上安装</h2><p class="note">在 Safari 中打开网页，点击分享按钮，选择“添加到主屏幕”，然后从主屏幕打开听页。</p><div class="install-note">${'serviceWorker'in navigator&&window.isSecureContext?'界面可离线保存，音频和逐字稿保存在当前设备。':'当前地址不支持完整离线安装，请使用 HTTPS 网页。'}</div></section><section class="panel"><h2>电脑转写</h2><p class="note">电脑临时处理音频，生成逐字稿和时间轴。导出的文件和原音频一起导入手机，之后不需要电脑在线。</p><button class="primary full" id="computer-transcribe" ${backend?'':'disabled'}>${backend?'打开电脑转写':'请在电脑启动本地转写工具'}</button>${backend?'<button class="secondary full section-title" id="podcast-import">导入播客 RSS / 音频链接</button>':''}</section></div>`;on('#font','change',async e=>{prefs.font=e.target.value;await savePrefs();});on('#imm-font','change',async e=>{prefs.immFont=e.target.value;await savePrefs();});on('#persist-storage','click',async()=>{const granted=await navigator.storage?.persist?.();toast(granted?'已获得长期保存权限':'系统暂未授予长期保存权限，请保留备份');renderSettings();});on('#export-backup','click',exportBackup);on('#import-backup','click',importBackup);on('#computer-transcribe','click',()=>computerTranscription());on('#podcast-import','click',podcastImport);}
async function exportBackup(){try{const episodes=await all('episodes'),cards=await all('cards');let offset=0;const entries=episodes.map(e=>{const{audio,...meta}=e;const entry={...meta,offset,bytes:audio.size,mime:audio.type};offset+=audio.size;return entry;});const json=new TextEncoder().encode(JSON.stringify({format:'tingye-backup-v1',episodes:entries,cards,preferences:prefs})),header=new Uint8Array(12);header.set(new TextEncoder().encode('TINGYE01'),0);new DataView(header.buffer).setUint32(8,json.length,true);download(new Blob([header,json,...episodes.map(e=>e.audio)],{type:'application/octet-stream'}),`听页备份-${new Date().toISOString().slice(0,10)}.tyb`);toast('请将备份保存到手机“文件”中');}catch(e){report(e);}}
function importBackup(){openModal('恢复备份','<input id="backup-file" type="file" accept=".tyb"><p class="note">恢复时会添加备份里的音频和词卡，不会覆盖现有资料。</p><button class="primary full" id="restore-backup">恢复到本机</button>');on('#restore-backup','click',async()=>{const b=$('#restore-backup');b.disabled=true;try{const file=$('#backup-file').files[0];if(!file||file.size<12)throw Error('请选择听页备份文件。');const header=await file.slice(0,12).arrayBuffer();if(new TextDecoder().decode(header.slice(0,8))!=='TINGYE01')throw Error('备份格式不正确。');const length=new DataView(header).getUint32(8,true);if(length>30*1048576||12+length>file.size)throw Error('备份文件不完整。');const meta=JSON.parse(await file.slice(12,12+length).text());validateBackup(meta,file.size-12-length);const idMap=new Map(),episodes=[];for(const item of meta.episodes){if(!LANG[item.language]||!Number.isSafeInteger(item.offset)||!Number.isSafeInteger(item.bytes)||item.offset<0||item.bytes<1||item.bytes>350*1048576||12+length+item.offset+item.bytes>file.size)throw Error('备份中的音频不完整。');validateTranscript({format:'tingye-transcript-v1',version:1,language:item.language,duration:item.duration,segments:item.segments||[]});const id=crypto.randomUUID();idMap.set(item.id,id);episodes.push({...item,id,audio:file.slice(12+length+item.offset,12+length+item.offset+item.bytes,item.mime||'audio/mpeg')});}const cards=meta.cards.filter(c=>idMap.has(c.episodeId)).map(c=>({...c,id:crypto.randomUUID(),episodeId:idMap.get(c.episodeId)}));const restoredPrefs=validatePreferences(meta.preferences);await saveBatch(episodes,cards,[{id:'preferences',value:restoredPrefs}]);prefs=restoredPrefs;applyPrefs();closeModal();navigate('library');toast(`已恢复 ${episodes.length} 段音频`);}catch(e){report(e);b.disabled=false;}});}
async function computerTranscription(existing){
  if(!backend){toast('请在电脑启动本地转写工具。');return;}
  const requestedAudio=existing;
  const savedJob=(await read('settings','transcription-job'))?.value;
  const pending=(!existing||(existing.id&&savedJob?.episodeId===existing.id))?savedJob:null;
  if(pending?.episodeId)existing=await read('episodes',pending.episodeId);
  openModal('电脑转写',`${pending?'<p class="note">继续查看上一次转写任务。</p>':existing?`<div class="file-meta">${esc(existing.title)}</div>`:'<label for="asr-audio">临时处理的音频</label><input id="asr-audio" type="file" accept="audio/*,.mp3,.m4a,.wav,.flac,.ogg">'}${pending?'':`<label for="asr-language">音频语言</label><select id="asr-language">${Object.entries(LANG).map(([c,n])=>`<option value="${c}" ${existing?.language===c?'selected':''}>${n}</option>`).join('')}</select><p class="note">处理后清理临时音频。逐字稿包含时间轴，可导入手机。</p><button class="primary full" id="start-asr">开始本地转写</button>`}<div id="asr-result"></div><button class="secondary full section-title" id="new-asr" ${pending?'':'hidden'}>开始新的转写</button>`);
  const serial=modalSerial;
  const alive=()=>modal.open&&modalSerial===serial&&!!$('#asr-result');
  on('#new-asr','click',async()=>{await remove('settings','transcription-job');await computerTranscription(requestedAudio);});
  async function poll(id){
    if(!alive())return;
    try{
      const r=await fetch(new URL(`api/jobs/${id}`,BASE)),job=await r.json();
      if(!alive())return;
      if(!r.ok)throw Error(job.detail||'读取任务失败。');
      $('#asr-result').innerHTML=`<div class="job"><strong>${esc(job.message)}</strong><progress max="100" value="${job.progress||0}"></progress><p class="note">${job.progress||0}%</p></div>`;
      if(job.state==='done'){
        $('#new-asr').hidden=false;
        $('#asr-result').innerHTML=`<div class="job"><strong>转写完成</strong><p class="note">${job.result.segments.length} 个句段 · 音频 ${time(job.result.duration)}</p><button class="primary full" id="download-asr">导出逐字稿与时间轴</button>${existing?.id?'<button class="secondary full section-title" id="attach-asr">用于当前音频</button>':''}</div>`;
        on('#download-asr','click',()=>download(new Blob([JSON.stringify(job.result,null,2)],{type:'application/json'}),`${job.result.title}.tingye.json`));
        on('#attach-asr','click',async()=>{try{await attachTranscript(existing,job.result);closeModal();await openEpisode(existing.id);}catch(e){report(e);}});
        return;
      }
      if(job.state==='error')throw Error(`${job.message}：${job.detail||''}`);
      jobTimer=setTimeout(()=>poll(id),1500);
    }catch(e){if(alive()){$('#new-asr').hidden=false;$('#asr-result').innerHTML=`<p class="note">${esc(e.message)}</p>`;report(e);}}
  }
  if(pending?.id){await poll(pending.id);return;}
  on('#start-asr','click',async()=>{
    const button=$('#start-asr');button.disabled=true;
    try{
      const file=existing?new File([existing.audio],existing.filename,{type:existing.audio.type}):$('#asr-audio').files[0];
      if(!file)throw Error('请选择音频文件。');if(file.size>350*1048576)throw Error('音频不能超过 350 MB。');
      const form=new FormData();form.append('audio',file);form.append('language',$('#asr-language').value);
      $('#asr-result').innerHTML='<p class="note">正在提交给本机转写工具…</p>';
      const response=await fetch(new URL('api/jobs',BASE),{method:'POST',body:form}),result=await response.json();
      if(!response.ok)throw Error(result.detail||'任务未能启动。');
      await write('settings',{id:'transcription-job',value:{id:result.id,episodeId:existing?.id||null}});
      if(alive()){button.hidden=true;await poll(result.id);}
    }catch(e){if(alive()){report(e);button.disabled=false;}}
  });
}
function podcastImport(){
  openModal('导入播客','<label for="podcast-url">播客 RSS 或直接音频链接</label><input id="podcast-url" type="url" placeholder="https://…"><button class="primary full section-title" id="load-podcast">读取单集</button><div id="podcast-results"></div>');
  const serial=modalSerial;
  on('#load-podcast','click',async()=>{
    const b=$('#load-podcast');b.disabled=true;
    try{
      const url=$('#podcast-url').value.trim(),r=await fetch(new URL(`api/podcast?url=${encodeURIComponent(url)}`,BASE)),data=await r.json();
      if(modalSerial!==serial)return;
      if(!r.ok)throw Error(data.detail||'读取失败');if(!data.episodes.length)throw Error('没有找到可导入的音频。');
      $('#podcast-results').innerHTML=`<div class="stack section-title">${data.episodes.map((e,i)=>`<button class="secondary" data-podcast="${i}">${esc(e.title)}</button>`).join('')}</div><label for="podcast-lang">音频语言</label><select id="podcast-lang">${Object.entries(LANG).map(([c,n])=>`<option value="${c}">${n}</option>`).join('')}</select>`;
      document.querySelectorAll('[data-podcast]').forEach(button=>button.onclick=async()=>{
        button.disabled=true;
        const language=$('#podcast-lang').value;
        try{
          const item=data.episodes[Number(button.dataset.podcast)],r=await fetch(new URL(`api/audio-fetch?url=${encodeURIComponent(item.url)}`,BASE));
          if(!r.ok)throw Error((await r.json()).detail||'无法导入音频');
          const blob=await r.blob();if(modalSerial!==serial)return;
          const ext=({'audio/wav':'.wav','audio/x-wav':'.wav','audio/mp4':'.m4a','audio/flac':'.flac','audio/ogg':'.ogg'})[blob.type]||'.mp3';
          const filename=item.title.slice(0,180).replace(/[\\/:*?"<>|]/g,'_')+ext;
          const staged={title:item.title,filename,audio:blob,language};
          openModal('播客音频已准备',`<p class="note">${esc(item.title)}</p><p class="note">先保存原音频，再生成逐字稿。将两个文件一起传到手机即可。</p><div class="stack"><button class="secondary full" id="save-podcast-audio">保存原音频文件</button><button class="primary full" id="transcribe-podcast">生成逐字稿与时间轴</button></div>`);
          on('#save-podcast-audio','click',()=>download(blob,filename));
          on('#transcribe-podcast','click',()=>computerTranscription(staged));
        }catch(e){if(modalSerial===serial){report(e);button.disabled=false;}}
      });
    }catch(e){if(modalSerial===serial)report(e);}if(modalSerial===serial)b.disabled=false;
  });
}
async function navigate(target){resetClip();if(immersive)toggleImmersive();$('.player-dock')?.remove();view=target;location.hash=target;if(target==='library')await renderLibrary();if(target==='cards')await renderCards();if(target==='settings')await renderSettings();window.scrollTo(0,0);}
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav).catch(report));window.addEventListener('hashchange',()=>{const hash=location.hash.slice(1);if(hash.startsWith('audio/')){const id=hash.slice(6);if(episode?.id!==id||view!=='player')openEpisode(id).catch(report);}else if(['library','cards','settings'].includes(hash)&&view!==hash)navigate(hash).catch(report);});
document.addEventListener('keydown',e=>{if(modal.open||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.code==='Space'&&episode){e.preventDefault();togglePlay();}if(e.key==='ArrowRight'&&episode)jump(Math.min(episode.segments.length-1,current+1),true);if(e.key==='ArrowLeft'&&episode)jump(Math.max(0,current-1),true);if(e.key==='Escape'&&immersive)toggleImmersive();if(e.key.toLowerCase()==='r'&&episode)jump(Math.max(0,current),true);});
function connectionState(){$('#connection').textContent=navigator.onLine?'本机保存':'离线 · 本机保存';}window.addEventListener('online',connectionState);window.addEventListener('offline',connectionState);connectionState();applyPrefs();
try{if(['localhost','127.0.0.1'].includes(location.hostname)){const r=await fetch(new URL('api/status',BASE));backend=r.ok&&(await r.json()).available===true;}}catch{}
if('serviceWorker'in navigator&&window.isSecureContext)navigator.serviceWorker.register(new URL('sw.js',BASE),{scope:BASE.pathname}).catch(console.error);
if('mediaSession'in navigator){for(const [name,handler] of [['play',()=>audio.play().catch(report)],['pause',()=>audio.pause()],['seekto',d=>{if(Number.isFinite(d.seekTime)){resetClip();current=-1;audio.currentTime=Math.min(episode?.duration||0,Math.max(0,d.seekTime));updatePlayback();}}],['previoustrack',()=>episode&&jump(Math.max(0,current-1),true)],['nexttrack',()=>episode&&jump(Math.min(episode.segments.length-1,current+1),true)]])try{navigator.mediaSession.setActionHandler(name,handler);}catch{}}
try{const context=document.modelContext;if(context?.registerTool){context.registerTool({name:'list_saved_audio',description:'List audio saved on the current device without returning audio bytes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{if(Object.keys(input||{}).length)throw Error('No input properties accepted');return (await all('episodes')).map(e=>({id:e.id,title:e.title,language:e.language,duration:e.duration,progress:e.progress,hasTranscript:!!e.segments?.length}));}});context.registerTool({name:'seek_current_audio',description:'Seek the current audio without starting playback.',inputSchema:{type:'object',properties:{seconds:{type:'number',minimum:0}},required:['seconds'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!episode||!Number.isFinite(input?.seconds)||input.seconds<0||input.seconds>episode.duration||Object.keys(input).some(k=>k!=='seconds'))throw Error('A current audio and an in-range seconds value are required');resetClip();current=-1;audio.currentTime=input.seconds;updatePlayback();await saveProgress();return{episodeId:episode.id,seconds:audio.currentTime};}});}}catch(e){console.warn('Optional browser integration unavailable',e);}
const initial=location.hash.slice(1);if(initial.startsWith('audio/'))await openEpisode(initial.slice(6)).catch(()=>renderLibrary());else await navigate(['cards','settings'].includes(initial)?initial:'library');

