const CACHE='tingye-shell-2026.10.04.09';
const ASSETS=['./','./index.html','./styles.css','./styles.css?v=2026.10.04.09','./app.js','./app.js?v=2026.10.04.09','./client.js','./client.js?v=2026.10.04.09','./transcript-batch.js','./transcript-batch.js?v=2026.10.04.09','./db.js','./db.js?v=2026.10.04.09','./validate.js','./validate.js?v=2026.10.04.09','./lexicon.js','./practice.js','./practice.js?v=2026.10.04.09','./theme.js','./furigana.js','./transcript-edit.js','./playlist.js','./playlist.js?v=2026.10.04.09','./playlist-sheet.js?v=2026.10.04.09','./playback-list.js?v=2026.10.04.09','./segment-edit.js','./segment-edit.js?v=2026.10.04.09','./transcript-edit.js?v=2026.10.04.09','./sentence-boundaries.js?v=2026.10.04.09','./reader-gestures.js','./reader-gestures.js?v=2026.10.04.09','./folders.js','./drag-order.js','./cards.js','./audio-storage.js','./audio-storage.js?v=2026.10.04.09','./audio-lifecycle.js?v=2026.10.04.09','./list-position.js?v=2026.10.04.09','./audio-media.js','./audio-media.js?v=2026.10.04.09','./browser-model-cleanup.js?v=2026.10.04.09','./manifest.webmanifest','./icon.svg','./icons/icon-192.png','./icons/icon-512.png'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('tingye-shell-')&&key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url);
 if(event.request.method!=='GET'||url.origin!==self.location.origin||url.pathname.includes('/api/'))return;
 if(event.request.mode==='navigate'){event.respondWith(fetch(event.request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put('./index.html',copy));}return response;}).catch(()=>caches.match('./index.html')));return;}
 if(ASSETS.some(asset=>new URL(asset,self.registration.scope).href===url.href)){event.respondWith(fetch(event.request,{cache:'no-cache'}).then(async response=>{if(response.ok)await (await caches.open(CACHE)).put(event.request,response.clone());return response;}).catch(()=>caches.match(event.request)));}
});
